---

        version: "3"

        services:
#----------------------------NGINX---------------------------------------#
                nginx:
                        build: 
                                context: requirements/nginx
                        ports:
                                - 9000:9000
                        env_file:
                                - .env
                        depends_on:
                                - wordpress
                        networks:
                                - inception
                        restart: always

#----------------------------MARIADB-------------------------------------#
                mariadb:
                        build:
                                context: requirements/mariadb
                        ports:
                                - 3306:3306
                        env_file:
                                - .env
                        networks:
                                - inception
                        restart: always

#----------------------------WORDPRESS-----------------------------------#
                wordpress:
                        build:
                                context: requirements/wordpress
                        ports:
                                - 3306:9000
                        env_file:
                                - .env
                        depends_on:
                                - mariadb
                        networks:
                                - inception
                        restart: always

#----------------------------VOLUMES-------------------------------------#
                #volumes:

#----------------------------NETWORKS--0---------------------------------#
                networks:
                        inception:
                                name: inception
                                driver: bridge
