---
        version: "3"

        services:
#----------------------------NGINX---------------------------------------#
                nginx:
                        build: 
                                context: requirements/nginx
                        ports:
                                - 443:443
                        env_file:
                                - .env
                        depends_on:
                                - wordpress
                        networks:
                                - inception
                        restart: always

#----------------------------MARIADB-------------------------------------#
                mariadb:
                        build:
                                context: requirements/mariadb
                        env_file:
                                - .env
                        networks:
                                - inception
                        expose:
                                - "9000"
                        volumes:
                                - mariadb_data:/var/lib/mysql
                        restart: always

#----------------------------WORDPRESS-----------------------------------#
                wordpress:
                        build:
                                context: requirements/wordpress
                        env_file:
                                - .env
                        depends_on:
                                - mariadb
                        networks:
                                - inception
                        expose:
                                - "9000"
                        volumes:
                                - wp_data:/var/www/html
                        restart: always

#----------------------------VOLUMES-------------------------------------#
                volumes:
                        data_mariadb:
                                driver_opts:
                                        type: "none"
                                        o: "bind"
                                        device: "~/data/mariadb_data"

                        wp-content:
                                driver_opts:
                                        type: "none"
                                        o: "bind"
                                        device: "~/data/wp_data"

#----------------------------NETWORKS--0---------------------------------#
                networks:
                        inception:
                                name: inception
                                driver: bridge
