---
        version: "3"

        services:
#----------------------------NGINX---------------------------------------#
                nginx:
                        container_name: nginx
                        build: 
                                context: ./requirements/nginx
                        ports:
                                - 443:443
                        env_file:
                                - .env
                        depends_on:
                                - wordpress
                        networks:
                                - inception
                        restart: always

#----------------------------MARIADB-------------------------------------#
                mariadb:
                        container_name: mariadb
                        build:
                                context: ./requirements/mariadb
                        env_file:
                                - .env
                        networks:
                                - inception
                        expose:
                                - "9000"
                        volumes:
                                - mariadb_data:/var/lib/mysql
                        restart: always

#----------------------------WORDPRESS-----------------------------------#
                wordpress:
                        container_name: wordpress
                        build:
                                context: ./requirements/wordpress
                        env_file:
                                - .env
                        depends_on:
                                - mariadb
                        networks:
                                - inception
                        expose:
                                - "9000"
                        volumes:
                                - wp_data:/var/www/html/wordpress
                        restart: always

#----------------------------VOLUMES-------------------------------------#
        volumes:
                mariadb_data:
                        driver_opts:
                                type: "none"
                                o: "bind"
                                device: "/home/$USER/data/mariadb_data"

                wp_data:
                        driver_opts:
                                type: "none"
                                o: "bind"
                                device: "/home/$USER/data/wp_data"

#----------------------------NETWORKS--0---------------------------------#
        networks:
                inception:
                        driver: bridge
