version: "3.5"

networks:
    inception: {}

services:

#---------------------NGINX------------------------#
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress
            - mariadb
        restart: on-failure


#-------------------WORDPRESS---------------------#
    wordpress:
        container_name: wordpress
        image: wordpress
        build: 
            context: ./requirements/wordpress
        env_file:
            - .env
        networks:
            - inception
        depends_on:
            - mariadb
        restart: on-failure
        volumes:
            - wp_data:/var/www/html/wordpress


#-------------------MARIADB---------------------#
    mariadb:
        container_name: mariadb
        image: mariadb
        build: 
            context: ./requirements/mariadb
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - mariadb_data:/var/lib/mysql
        restart: on-failure

volumes:
    mariadb_data:
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/$USER/data/mariadb_data"

    wp_data:
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/$USER/data/wp_data"
